/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesTrendingRouteImport } from './routes/movies/trending'
import { Route as MoviesSearchRouteImport } from './routes/movies/search'
import { Route as MoviesPopularRouteImport } from './routes/movies/popular'
import { Route as MoviesMovieIdRouteImport } from './routes/movies/$movieId'
import { Route as profileProfileRouteImport } from './routes/(profile)/profile'
import { Route as profileProfileSettingsRouteImport } from './routes/(profile)/profile.settings'
import { Route as profileProfileMessagesRouteImport } from './routes/(profile)/profile.messages'
import { Route as profileProfileInfosRouteImport } from './routes/(profile)/profile.infos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesTrendingRoute = MoviesTrendingRouteImport.update({
  id: '/movies/trending',
  path: '/movies/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesSearchRoute = MoviesSearchRouteImport.update({
  id: '/movies/search',
  path: '/movies/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesPopularRoute = MoviesPopularRouteImport.update({
  id: '/movies/popular',
  path: '/movies/popular',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/movies/popular.lazy').then((d) => d.Route),
)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const profileProfileRoute = profileProfileRouteImport.update({
  id: '/(profile)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const profileProfileSettingsRoute = profileProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => profileProfileRoute,
} as any)
const profileProfileMessagesRoute = profileProfileMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => profileProfileRoute,
} as any)
const profileProfileInfosRoute = profileProfileInfosRouteImport.update({
  id: '/infos',
  path: '/infos',
  getParentRoute: () => profileProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof profileProfileRouteWithChildren
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/popular': typeof MoviesPopularRoute
  '/movies/search': typeof MoviesSearchRoute
  '/movies/trending': typeof MoviesTrendingRoute
  '/profile/infos': typeof profileProfileInfosRoute
  '/profile/messages': typeof profileProfileMessagesRoute
  '/profile/settings': typeof profileProfileSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof profileProfileRouteWithChildren
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/popular': typeof MoviesPopularRoute
  '/movies/search': typeof MoviesSearchRoute
  '/movies/trending': typeof MoviesTrendingRoute
  '/profile/infos': typeof profileProfileInfosRoute
  '/profile/messages': typeof profileProfileMessagesRoute
  '/profile/settings': typeof profileProfileSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(profile)/profile': typeof profileProfileRouteWithChildren
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/popular': typeof MoviesPopularRoute
  '/movies/search': typeof MoviesSearchRoute
  '/movies/trending': typeof MoviesTrendingRoute
  '/(profile)/profile/infos': typeof profileProfileInfosRoute
  '/(profile)/profile/messages': typeof profileProfileMessagesRoute
  '/(profile)/profile/settings': typeof profileProfileSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/movies/$movieId'
    | '/movies/popular'
    | '/movies/search'
    | '/movies/trending'
    | '/profile/infos'
    | '/profile/messages'
    | '/profile/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/movies/$movieId'
    | '/movies/popular'
    | '/movies/search'
    | '/movies/trending'
    | '/profile/infos'
    | '/profile/messages'
    | '/profile/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(profile)/profile'
    | '/movies/$movieId'
    | '/movies/popular'
    | '/movies/search'
    | '/movies/trending'
    | '/(profile)/profile/infos'
    | '/(profile)/profile/messages'
    | '/(profile)/profile/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  profileProfileRoute: typeof profileProfileRouteWithChildren
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  MoviesPopularRoute: typeof MoviesPopularRoute
  MoviesSearchRoute: typeof MoviesSearchRoute
  MoviesTrendingRoute: typeof MoviesTrendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/trending': {
      id: '/movies/trending'
      path: '/movies/trending'
      fullPath: '/movies/trending'
      preLoaderRoute: typeof MoviesTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/search': {
      id: '/movies/search'
      path: '/movies/search'
      fullPath: '/movies/search'
      preLoaderRoute: typeof MoviesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/popular': {
      id: '/movies/popular'
      path: '/movies/popular'
      fullPath: '/movies/popular'
      preLoaderRoute: typeof MoviesPopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(profile)/profile': {
      id: '/(profile)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof profileProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(profile)/profile/settings': {
      id: '/(profile)/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof profileProfileSettingsRouteImport
      parentRoute: typeof profileProfileRoute
    }
    '/(profile)/profile/messages': {
      id: '/(profile)/profile/messages'
      path: '/messages'
      fullPath: '/profile/messages'
      preLoaderRoute: typeof profileProfileMessagesRouteImport
      parentRoute: typeof profileProfileRoute
    }
    '/(profile)/profile/infos': {
      id: '/(profile)/profile/infos'
      path: '/infos'
      fullPath: '/profile/infos'
      preLoaderRoute: typeof profileProfileInfosRouteImport
      parentRoute: typeof profileProfileRoute
    }
  }
}

interface profileProfileRouteChildren {
  profileProfileInfosRoute: typeof profileProfileInfosRoute
  profileProfileMessagesRoute: typeof profileProfileMessagesRoute
  profileProfileSettingsRoute: typeof profileProfileSettingsRoute
}

const profileProfileRouteChildren: profileProfileRouteChildren = {
  profileProfileInfosRoute: profileProfileInfosRoute,
  profileProfileMessagesRoute: profileProfileMessagesRoute,
  profileProfileSettingsRoute: profileProfileSettingsRoute,
}

const profileProfileRouteWithChildren = profileProfileRoute._addFileChildren(
  profileProfileRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  profileProfileRoute: profileProfileRouteWithChildren,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  MoviesPopularRoute: MoviesPopularRoute,
  MoviesSearchRoute: MoviesSearchRoute,
  MoviesTrendingRoute: MoviesTrendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
